RonanTurtle:
  background_b: 255
  background_g: 86
  background_r: 69
rosdistro: 'noetic

  '
roslaunch:
  uris:
    host_ronan_virtualbox__36157: http://ronan-VirtualBox:36157/
rosversion: '1.15.15

  '
run_id: 37c72c1e-9915-11ed-a2f5-c55faf92c3dc
turtlesim:
  background_b: 255
  background_g: 86
  background_r: 150
